### ISSUE TITLE
Identifying MiniBufExplorer's buffer

### ISSUE THREAD

**Issue by greduan** [weynhamz/vim-plugin-minibufexpl#2]
Hi, I ask this question from a plugin compatibility stand point.

Right now I'm doing [my own fork](https://github.com/Greduan/vim_number-toggle) of the [numbertoggle](https://github.com/jeffkreeftmeijer/vim-numbertoggle) for Vim. However I've run across the problem that I can't recognize which buffer this is.

I need to recognize MiniBufExplorer's buffer, and deactivate any functionality on that buffer only. What would be the best way to do this?

BTW, would the same method apply for things like NERDtree?

Thanks! I need an answer soon BTW. :wink:

**Comment by weynhamz** [comment]
You can idenetify a plugin buffer by their buffer name or the file type. Usually a plugin buffer will have a unique buffer name, like MBE. For NERDTree, because you can open multiple NERDTree buffers, they do not have a unique buffer name, but all these buffers have same filetype 'nerdtree', so is the Tagbar (tagbar), and in my develop branch of MBE, the filetype is also been set to 'minibufexpl'.

```
#Get buffer name for a window
bufname(winbufnr(window_number))
#Get file type for a window
getwinvar(window_number, "&ft")
#Get buffer name for a buffer
bufname(buffer_number)
#Get file type for a buffer
getbufvar(buffer_number,"&ft")
```

If you just want to identify whether a buffer is a plugin buffer or not, you can see MBE's "IsBufferIgnored()" Function in my develop branch.

**Comment by greduan** [comment]
Is there a way to recognize it, without using your `develop` branch?

I want this to be as widely compatible as possible, if possible be compatible with the original MiniBufExplorer.

**Comment by weynhamz** [comment]
`bufname('%') == '-MiniBufExplorer-'` will do.

**Comment by greduan** [comment]
Excellent, thanks!

Be sure to check out the plugin once it's finished. :wink:

**Comment by weynhamz** [comment]
Definitely, the plugin looks very useful.

**Comment by greduan** [comment]
@techlivezheng Oh, I said to be sure to check it out. Not sure if you did or not yet, but if not, it's finished, just waiting for a pull request. :)
https://github.com/Greduan/vim-numbertoggle
